# Generated by Django 5.2.15 on 2026-06-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_role_employee_user'),
        ('organisation', '0004_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dynamic_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organisation.role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
