# Generated by Django 5.2.15 on 2026-06-20 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_phone'),
        ('payroll', '0005_payrollsettings_taxregimeslab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='payroll.salarystructure'),
        ),
    ]
