# Generated by Django 5.2.15 on 2026-06-22 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeedocument_employeeexit_employeetransfer'),
        ('payroll', '0006_componentrule_prorate_alter_componentrule_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc', models.IntegerField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_history', to='employees.employee')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.salarystructure')),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
    ]
