# Generated by Django 5.2.15 on 2026-06-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
