# Generated by Django 5.2.15 on 2026-06-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_offertemplate_offerletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
