# Generated by Django 5.2.15 on 2026-06-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_offerletter_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('Service Employee', 'Service Employee'), ('Normal Employee', 'Normal Employee')], default='Normal Employee', max_length=50),
        ),
    ]
