# Generated by Django 5.2.15 on 2026-06-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bonus_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='bonus_type',
            field=models.CharField(blank=True, choices=[('Fixed Amount', 'Fixed Amount'), ('Percentage', 'Percentage'), ('Monthly Salary', 'Monthly Salary')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bonus_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
