# Generated by Django 5.2.15 on 2026-06-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_bonus_applicable_employee_bonus_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bonus_months',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
