# Generated by Django 5.2.15 on 2026-07-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_bonus_months_employee_pf_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='offertemplate',
            name='body_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
