# Generated by Django 5.2.15 on 2026-07-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_offertemplate_body_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tax_regime',
            field=models.CharField(choices=[('New', 'New Regime'), ('Old', 'Old Regime')], default='New', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_saving_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total approved tax savings (e.g. 80C) used only for Old Regime calculations.', max_digits=12),
        ),
    ]
