# Generated by Django 5.2.15 on 2026-07-07 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_employee_tax_regime_employee_tax_saving_deductions'),
        ('organisation', '0009_organization_entity_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organisation.organization'),
        ),
    ]
