# Generated by Django 5.2.15 on 2026-07-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_employee_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
