# Generated by Django 5.2.15 on 2026-07-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_notification_related_employee_id'),
        ('organisation', '0010_alter_entity_organization_site_activate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='enrolled_sites',
            field=models.ManyToManyField(blank=True, related_name='enrolled_employees', to='organisation.site'),
        ),
        migrations.AlterField(
            model_name='employeeexit',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexit',
            name='resignation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeeexit',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
