# Generated by Django 5.2.15 on 2026-07-25 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_employee_created_at_employee_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_by', models.CharField(default='System', max_length=255)),
                ('action', models.CharField(max_length=50)),
                ('changes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='employees.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
