# Generated by Django 5.2.15 on 2026-08-06 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_offertemplate_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='offer_letters/'),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.offertemplate'),
        ),
    ]
