# Generated by Django 5.2.15 on 2026-08-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_offerletter_pdf_file_offerletter_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='offertemplate',
            name='footer_html',
            field=models.TextField(blank=True, help_text='Custom HTML for the PDF footer', null=True),
        ),
        migrations.AddField(
            model_name='offertemplate',
            name='footer_image',
            field=models.ImageField(blank=True, null=True, upload_to='offer_templates/footers/'),
        ),
        migrations.AddField(
            model_name='offertemplate',
            name='header_html',
            field=models.TextField(blank=True, help_text='Custom HTML for the PDF header', null=True),
        ),
        migrations.AddField(
            model_name='offertemplate',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='offer_templates/headers/'),
        ),
    ]
