# Generated by Django 5.2.15 on 2026-08-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_offertemplate_footer_html_offertemplate_footer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offertemplate',
            name='footer_image_align',
            field=models.CharField(default='center', help_text='left, right, or center', max_length=20),
        ),
        migrations.AddField(
            model_name='offertemplate',
            name='footer_image_width',
            field=models.CharField(default='535', help_text='Width in points or px', max_length=50),
        ),
        migrations.AddField(
            model_name='offertemplate',
            name='header_image_align',
            field=models.CharField(default='center', help_text='left, right, or center', max_length=20),
        ),
        migrations.AddField(
            model_name='offertemplate',
            name='header_image_width',
            field=models.CharField(default='535', help_text='Width in points or px', max_length=50),
        ),
    ]
