# Generated by Django 5.2.15 on 2026-06-19 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_rename_name_designation_title_remove_branch_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_late_minutes', models.IntegerField(default=15)),
                ('half_day_hours', models.DecimalField(decimal_places=2, default=4.0, max_digits=4)),
                ('full_day_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('require_face', models.BooleanField(default=True)),
                ('require_qr', models.BooleanField(default=True)),
                ('require_gps', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_attendance_policy', to='organisation.entity')),
                ('site', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policy', to='organisation.site')),
            ],
        ),
    ]
