# Generated by Django 5.2.15 on 2026-06-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_attendancepolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('access_scope', models.CharField(default='Self', max_length=50)),
                ('dashboard_type', models.CharField(blank=True, max_length=50, null=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('cross_department_access', models.BooleanField(default=False)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='organisation.department')),
            ],
        ),
    ]
