# Generated by Django 5.2.15 on 2026-06-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
