# Generated by Django 5.2.15 on 2026-06-26 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='hierarchy_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_roles', to='organisation.role'),
        ),
    ]
