# Generated by Django 5.2.15 on 2026-06-29 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_notification_options'),
        ('organisation', '0006_role_hierarchy_level_role_reporting_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policy', to='employees.employee'),
        ),
    ]
