# Generated by Django 5.2.15 on 2026-07-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_attendancepolicy_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='ot_applicable_after_hours',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=4),
        ),
    ]
