# Generated by Django 5.2.15 on 2026-07-07 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_attendancepolicy_ot_applicable_after_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=150, null=True)),
                ('site_location', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('white_label_enabled', models.BooleanField(default=False)),
                ('sub_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('solution_type', models.CharField(blank=True, max_length=50, null=True)),
                ('solution_for', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_term', models.CharField(blank=True, max_length=50, null=True)),
                ('rate_of_billing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_cycle', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('project_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('billing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='organisation.organization'),
        ),
    ]
