# Generated by Django 5.2.15 on 2026-07-18 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_alter_entity_organization_site_activate_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='designation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
