# Generated by Django 5.2.15 on 2026-08-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_org', '0001_initial'),
        ('organisation', '0011_alter_branch_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='admin_org.organization'),
        ),
    ]
