# Generated by Django 5.2.15 on 2026-08-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_role_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='branding_text',
            field=models.CharField(blank=True, default='PeoplePulse HRMS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site_logos/'),
        ),
    ]
