# Generated by Django 5.2.15 on 2026-09-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0013_site_branding_text_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='bypass_geofence',
            field=models.BooleanField(default=False),
        ),
    ]
