# Generated by Django 5.2.15 on 2026-09-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_employee_photo'),
        ('organisation', '0014_attendancepolicy_bypass_geofence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancepolicy',
            name='bypass_geofence',
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='wfh_employees',
            field=models.ManyToManyField(blank=True, help_text='Employees granted Work From Home privileges to bypass geofence.', related_name='wfh_policies', to='employees.employee'),
        ),
    ]
