# Generated by Django 5.2.15 on 2026-09-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0015_remove_attendancepolicy_bypass_geofence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='face_match_threshold',
            field=models.DecimalField(decimal_places=2, default=95.0, help_text='Strict accuracy percentage required for face verification', max_digits=5),
        ),
    ]
