# Generated by Django 5.2.15 on 2026-09-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0016_attendancepolicy_face_match_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_saturday_working',
            field=models.BooleanField(default=False),
        ),
    ]
