# Generated by Django 5.2.15 on 2026-10-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0017_site_is_saturday_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_sub_site',
            field=models.BooleanField(default=False),
        ),
    ]
