# Generated by Django 5.2.15 on 2026-10-05 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0018_site_is_sub_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organisation.site'),
        ),
    ]
