# Generated by Django 5.2.15 on 2026-06-23 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0005_faceprofile_accessibility_profile_and_more'),
        ('employees', '0007_compensationhistory'),
        ('payroll', '0007_componentrule_calc_componentrule_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTApprovalRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_hours_for_hr', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('min_hours_for_finance', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='OTEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('multiplier_applied', models.DecimalField(decimal_places=2, max_digits=4)),
                ('converted_to_comp_off', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OTPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('weekend_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('holiday_multiplier', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('rounding_policy', models.CharField(choices=[('1', 'Nearest Minute'), ('5', 'Nearest 5 Minutes'), ('15', 'Nearest 15 Minutes'), ('30', 'Nearest 30 Minutes')], default='15', max_length=5)),
                ('auto_deduct_break_mins', models.IntegerField(default=0)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTThresholdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('STD_DEV', 'Standard Deviation'), ('PERCENTILE', 'Percentile'), ('FIXED', 'Fixed Cap')], default='STD_DEV', max_length=20)),
                ('window_days', models.IntegerField(default=90, help_text='Historical window for baseline')),
                ('multiplier_sensitivity', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CompOffBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OTAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text='e.g. OTRequest, OTPolicy', max_length=50)),
                ('entity_id', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hash_signature', models.CharField(help_text='SHA-256 chaining for immutability', max_length=64)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompOffTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('Lapse', 'Lapse'), ('Encash', 'Encash')], max_length=10)),
                ('days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ot_engine.compoffbalance')),
                ('ot_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ot_engine.otentry')),
            ],
        ),
        migrations.CreateModel(
            name='OTRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Flagged', 'Flagged')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.dailyattendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.AddField(
            model_name='otentry',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ot_engine.otrequest'),
        ),
        migrations.CreateModel(
            name='OTApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Manager', 'Manager'), ('HR', 'HR'), ('Finance', 'Finance')], max_length=20)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='ot_engine.otrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RetroOTEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusted_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField()),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.dailyattendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('original_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ot_engine.otentry')),
                ('target_payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollrun')),
            ],
        ),
        migrations.CreateModel(
            name='OTPayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ot_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ot_engine.otentry')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollrun')),
                ('retro_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ot_engine.retrootentry')),
            ],
        ),
    ]
