# Generated by Django 5.2.15 on 2026-06-19 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organisation', '0002_rename_name_designation_title_remove_branch_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('annual_entitlement', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('carry_forward_allowed', models.BooleanField(default=False)),
                ('max_carry_forward', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leaves/attachments/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('manager_comments', models.TextField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.entity')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.site')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaves.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('remaining_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('year', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype')),
            ],
            options={
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
