# Generated by Django 5.2.15 on 2026-06-22 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
        ('organisation', '0005_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('site', models.ForeignKey(blank=True, help_text='Leave blank if global holiday', null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.site')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'site')},
            },
        ),
    ]
