# Generated by Django 5.2.15 on 2026-06-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenured_years_threshold', models.IntegerField(default=5, help_text='Years required to be considered tenured')),
                ('tenured_annual_leaves', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('standard_annual_leaves', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('max_consecutive_leaves', models.IntegerField(default=3, help_text='Max consecutive days allowed without salary deduction')),
                ('exception_month', models.IntegerField(default=3, help_text='Month (1-12) where all accumulated leaves can be taken at once')),
            ],
            options={
                'verbose_name': 'Leave Policy Configuration',
                'verbose_name_plural': 'Leave Policy Configurations',
            },
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='salary_deduction_days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
