# Generated by Django 5.2.15 on 2026-06-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leavepolicyconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='sub_type',
            field=models.CharField(choices=[('Sick', 'Sick'), ('Casual', 'Casual'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
