# Generated by Django 5.2.15 on 2026-09-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_leaverequest_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicyconfiguration',
            name='is_saturday_working',
            field=models.BooleanField(default=False, help_text='Whether Saturday is considered a working day'),
        ),
    ]
