# Generated by Django 5.2.15 on 2026-09-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_leavepolicyconfiguration_is_saturday_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicyconfiguration',
            name='require_full_attendance_for_al',
            field=models.BooleanField(default=True, help_text='If False, employees earn AL even if absent.'),
        ),
    ]
