# Generated by Django 5.2.15 on 2026-06-20 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_compliancereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='calc',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('% of Basic', '% of Basic'), ('% of CTC', '% of CTC'), ('Balancing', 'Balancing')], max_length=20),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.salarystructure'),
        ),
    ]
