# Generated by Django 5.2.15 on 2026-06-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_salarystructure_alter_salarycomponent_calc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancereport',
            name='category',
            field=models.CharField(choices=[('Provident Fund', 'Provident Fund'), ('ESI', 'ESI'), ('Professional Tax', 'Professional Tax'), ('TDS', 'TDS')], default='Provident Fund', max_length=50),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='challan_number',
            field=models.CharField(blank=True, help_text='e.g. CIN 2410001234', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='filed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='period',
            field=models.CharField(default='October 2026', help_text='e.g. Oct 2026', max_length=20),
        ),
    ]
