# Generated by Django 5.2.15 on 2026-06-20 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_role_employee_user'),
        ('organisation', '0003_attendancepolicy'),
        ('payroll', '0004_compliancereport_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc_variance_threshold_percent', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('pf_wage_limit', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10)),
                ('esic_wage_limit', models.DecimalField(decimal_places=2, default=21000.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRegimeSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(choices=[('Old', 'Old'), ('New', 'New')], max_length=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('min_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RenameField(
            model_name='payrollrun',
            old_name='run_on',
            new_name='lock_date',
        ),
        migrations.RemoveField(
            model_name='payrollrun',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='payrollrun',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='payrollrun',
            name='gross',
        ),
        migrations.RemoveField(
            model_name='payrollrun',
            name='net',
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='checker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='run_type',
            field=models.CharField(choices=[('Live', 'Live'), ('Simulation', 'Simulation')], default='Live', max_length=20),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='challan_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='period',
            field=models.CharField(default='October 2026', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Processing', 'Processing'), ('Maker-Submitted', 'Maker-Submitted'), ('Checker-Approved', 'Checker-Approved'), ('Frozen', 'Frozen'), ('Disbursed', 'Disbursed')], default='Draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ComponentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Earning', 'Earning'), ('Deduction', 'Deduction')], max_length=20)),
                ('formula', models.TextField(help_text='Evaluated safely via simpleeval')),
                ('is_statutory', models.BooleanField(default=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.salarystructure')),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='organisation.department')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Split percentage', max_digits=5)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.costcenter')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PayrollGenerated', 'PayrollGenerated'), ('PayslipFrozen', 'PayslipFrozen'), ('RetroCreated', 'RetroCreated'), ('RuleChanged', 'RuleChanged'), ('ApprovalGranted', 'ApprovalGranted'), ('RunFailed', 'RunFailed'), ('SimulationRun', 'SimulationRun')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_trace', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollrun')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollrun')),
            ],
            options={
                'unique_together': {('employee', 'period', 'run')},
            },
        ),
        migrations.CreateModel(
            name='PayslipAllocationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.costcenter')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payslip')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payslip')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.componentrule')),
            ],
        ),
        migrations.CreateModel(
            name='RetroPayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_for_merge', models.BooleanField(default=False)),
                ('checker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_retros', to=settings.AUTH_USER_MODEL)),
                ('maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_retros', to=settings.AUTH_USER_MODEL)),
                ('original_payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retros', to='payroll.payslip')),
                ('target_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retro_merges', to='payroll.payrollrun')),
            ],
        ),
        migrations.CreateModel(
            name='RuleChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.componentrule')),
            ],
        ),
        migrations.CreateModel(
            name='RuleDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_deps', to='payroll.componentrule')),
                ('to_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_deps', to='payroll.componentrule')),
            ],
        ),
        migrations.CreateModel(
            name='SimulatedPayslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollrun')),
            ],
        ),
        migrations.CreateModel(
            name='SimulatedLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.componentrule')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.simulatedpayslip')),
            ],
        ),
        migrations.CreateModel(
            name='StatutoryRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollrun')),
            ],
        ),
        migrations.DeleteModel(
            name='SalaryComponent',
        ),
    ]
