# Generated by Django 5.2.15 on 2026-06-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payrollsettings_taxregimeslab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentrule',
            name='prorate',
            field=models.BooleanField(default=False, help_text='Multiply result by (present_days / total_days)'),
        ),
        migrations.AlterField(
            model_name='componentrule',
            name='type',
            field=models.CharField(choices=[('Earning', 'Earning'), ('Deduction', 'Deduction'), ('Employer Contribution', 'Employer Contribution')], max_length=50),
        ),
    ]
