# Generated by Django 5.2.15 on 2026-06-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_componentrule_prorate_alter_componentrule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentrule',
            name='calc',
            field=models.CharField(default='Fixed', max_length=50),
        ),
        migrations.AddField(
            model_name='componentrule',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='componentrule',
            name='formula',
            field=models.TextField(blank=True, help_text='Evaluated safely via simpleeval', null=True),
        ),
    ]
