# Generated by Django 5.2.15 on 2026-06-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_componentrule_calc_componentrule_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentrule',
            name='variable_code',
            field=models.CharField(blank=True, help_text='Immutable code used in formulas (e.g., BASIC_PAY)', max_length=50, null=True),
        ),
    ]
