# Generated by Django 5.2.15 on 2026-07-08 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_form16document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTCImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('successful', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('file_type', models.CharField(default='CSV', max_length=20)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Partial', 'Partial'), ('Failed', 'Failed')], default='Completed', max_length=20)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
