# Generated by Django 5.2.15 on 2026-06-25 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationNodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True, default=1)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('legacy_entity_id', models.IntegerField(blank=True, null=True)),
                ('legacy_department_id', models.IntegerField(blank=True, null=True)),
                ('legacy_project_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='org_engine.organizationnode')),
                ('node_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org_engine.organizationnodetype')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('performed_by_name', models.CharField(default='System', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('hash', models.CharField(blank=True, max_length=64, null=True)),
                ('new_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org_engine.organizationnode')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='org_engine.organizationnode')),
                ('old_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org_engine.organizationnode')),
            ],
        ),
    ]
