# Generated by Django 5.2.15 on 2026-06-26 05:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationnodetype',
            options={'ordering': ['level_order']},
        ),
        migrations.AddField(
            model_name='organizationauditlog',
            name='after_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationauditlog',
            name='before_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationnode',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizationnode',
            name='effective_from',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationnode',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationnode',
            name='legacy_employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationnode',
            name='legacy_role_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationnode',
            name='path',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organizationnodetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationnode',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizationnode',
            name='node_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='org_engine.organizationnodetype'),
        ),
    ]
