# Generated by Django 5.2.15 on 2026-06-26 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_engine', '0002_alter_organizationnodetype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_at_time', models.CharField(max_length=255)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='org_engine.organizationnode')),
                ('parent_at_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org_engine.organizationnode')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='NodeRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('Administrative', 'Administrative'), ('Functional', 'Functional'), ('Project', 'Project'), ('HR', 'HR'), ('Matrix', 'Matrix'), ('Temporary', 'Temporary'), ('Delegate', 'Delegate')], max_length=50)),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='org_engine.organizationnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='org_engine.organizationnode')),
            ],
            options={
                'unique_together': {('source_node', 'target_node', 'relationship_type', 'effective_from')},
            },
        ),
    ]
