# Generated by Django 5.2.15 on 2026-07-07 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Organization',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=150)),
                        ('status', models.CharField(default='Active', max_length=20)),
                        ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                        ('entity_name', models.CharField(blank=True, max_length=150, null=True)),
                        ('site_location', models.CharField(blank=True, max_length=150, null=True)),
                        ('country', models.CharField(blank=True, max_length=50, null=True)),
                        ('region', models.CharField(blank=True, max_length=50, null=True)),
                        ('state', models.CharField(blank=True, max_length=50, null=True)),
                        ('city', models.CharField(blank=True, max_length=50, null=True)),
                        ('zone', models.CharField(blank=True, max_length=50, null=True)),
                        ('white_label_enabled', models.BooleanField(default=False)),
                        ('sub_domain', models.CharField(blank=True, max_length=100, null=True)),
                        ('solution_type', models.CharField(blank=True, max_length=50, null=True)),
                        ('solution_for', models.CharField(blank=True, max_length=50, null=True)),
                        ('billing_term', models.CharField(blank=True, max_length=50, null=True)),
                        ('rate_of_billing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                        ('billing_cycle', models.CharField(blank=True, max_length=50, null=True)),
                        ('start_date', models.DateField(blank=True, null=True)),
                        ('project_duration', models.CharField(blank=True, max_length=50, null=True)),
                        ('end_date', models.DateField(blank=True, null=True)),
                        ('billing_date', models.DateField(blank=True, null=True)),
                        ('payment_status', models.CharField(default='Paid', max_length=20)),
                        ('current_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                        ('billing_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                        ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                        ('billing_address', models.TextField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'organisation_organization',
                    },
                ),
                migrations.CreateModel(
                    name='Invoice',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('invoice_number', models.CharField(max_length=50, unique=True)),
                        ('billing_date', models.DateField()),
                        ('due_date', models.DateField()),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('status', models.CharField(default='Paid', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='admin_org.organization')),
                    ],
                    options={
                        'db_table': 'organisation_invoice',
                    },
                ),
            ],
            database_operations=[]
        ),
    ]
