# Generated by Django 5.2.15 on 2026-09-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_org', '0002_organization_branding_text_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='require_full_attendance_for_al',
            field=models.BooleanField(default=True, help_text='If False, employees get AL even if absent.'),
        ),
    ]
