# Generated by Django 5.2.15 on 2026-06-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_regularizationrequest_attachment_dynamicqrtoken_and_more'),
        ('employees', '0007_compensationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punchlog',
            name='face_verified',
        ),
        migrations.RemoveField(
            model_name='punchlog',
            name='qr_verified',
        ),
        migrations.AddField(
            model_name='faceprofile',
            name='consent_granted',
            field=models.BooleanField(default=False, help_text='DPDPA/GDPR compliance explicit consent'),
        ),
        migrations.AddField(
            model_name='punchlog',
            name='qr_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='punchlog',
            name='verification_status',
            field=models.CharField(choices=[('VERIFIED', 'Verified'), ('PENDING_ML_INSTALL', 'Pending ML Install'), ('REJECTED', 'Rejected'), ('UNVERIFIED_LEGACY', 'Unverified Legacy')], default='PENDING_ML_INSTALL', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='punchlog',
            constraint=models.UniqueConstraint(fields=('employee', 'qr_token'), name='unique_punch_per_qr_token'),
        ),
    ]
