# Generated by Django 5.2.15 on 2026-06-22 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_punchlog_face_verified_and_more'),
        ('employees', '0007_compensationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceprofile',
            name='face_encoding',
        ),
        migrations.AddField(
            model_name='faceprofile',
            name='data_residency_shard',
            field=models.CharField(default='IN', help_text='e.g. EU for GDPR, IN for DPDPA', max_length=10),
        ),
        migrations.AddField(
            model_name='faceprofile',
            name='embedding_version',
            field=models.CharField(default='v2.0', max_length=10),
        ),
        migrations.AddField(
            model_name='faceprofile',
            name='encrypted_face_encodings',
            field=models.BinaryField(blank=True, help_text='AES encrypted JSON payload of multi-angle vectors (Front, Left, Right, Up, Down)', null=True),
        ),
        migrations.CreateModel(
            name='EnrollmentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(max_length=50)),
                ('hash_signature', models.CharField(help_text='SHA256 for audit integrity', max_length=64)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_audits', to='employees.employee')),
            ],
        ),
    ]
