# Generated by Django 5.2.15 on 2026-06-22 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_faceprofile_face_encoding_and_more'),
        ('employees', '0007_compensationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceprofile',
            name='accessibility_profile',
            field=models.BooleanField(default=False, help_text='If True, active liveness challenges are relaxed or bypassed for motor-impaired/neurodivergent employees.'),
        ),
        migrations.AddField(
            model_name='faceprofile',
            name='encrypted_dek',
            field=models.BinaryField(blank=True, help_text='Encrypted Data Encryption Key specific to this row', null=True),
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GRANTED', 'Granted'), ('REVOKED', 'Revoked')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ManualOverrideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Why did the AI fail? (e.g. Server down, False Rejection)')),
                ('is_approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approver_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides_approved_1', to='employees.employee')),
                ('approver_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides_approved_2', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_requests', to='employees.employee')),
            ],
        ),
    ]
