# Generated by Django 5.2.15 on 2026-06-29 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_shiftdefinition_shiftassignment'),
        ('organisation', '0006_role_hierarchy_level_role_reporting_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(default='Festival', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayRuleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_branches', models.ManyToManyField(blank=True, related_name='applicable_holidays', to='organisation.branch')),
                ('applicable_departments', models.ManyToManyField(blank=True, related_name='applicable_holidays', to='organisation.department')),
                ('applicable_entities', models.ManyToManyField(blank=True, related_name='applicable_holidays', to='organisation.entity')),
                ('applicable_roles', models.ManyToManyField(blank=True, related_name='applicable_holidays', to='organisation.role')),
                ('excluded_departments', models.ManyToManyField(blank=True, related_name='excluded_holidays', to='organisation.department')),
                ('excluded_roles', models.ManyToManyField(blank=True, related_name='excluded_holidays', to='organisation.role')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_groups', to='attendance.holiday')),
            ],
        ),
    ]
