# Generated by Django 5.2.15 on 2026-07-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_holiday_holidayrulegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftdefinition',
            name='ot_applicable_after_hours',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=4),
        ),
    ]
