# Generated by Django 5.2.15 on 2026-07-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_shiftdefinition_ot_applicable_after_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftdefinition',
            name='ot_applicable_after_hours',
        ),
    ]
