# Generated by Django 5.2.15 on 2026-09-08 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_holiday_site_shiftdefinition_site'),
        ('employees', '0027_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivenessLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liveness_lockout', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='StrictLivenessAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('punch_type', models.CharField(blank=True, max_length=10, null=True)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('is_wfh', models.BooleanField(default=False)),
                ('face_count', models.IntegerField(default=0)),
                ('laplacian_score', models.FloatField(blank=True, null=True)),
                ('moire_score', models.FloatField(blank=True, null=True)),
                ('specular_score', models.FloatField(blank=True, null=True)),
                ('onnx_liveness_score', models.FloatField(blank=True, null=True)),
                ('composite_score', models.FloatField(blank=True, null=True)),
                ('exif_edited_flag', models.BooleanField(default=False)),
                ('jpeg_double_compression', models.BooleanField(default=False)),
                ('velocity_kmh', models.FloatField(blank=True, null=True)),
                ('integrity_valid', models.BooleanField(default=True)),
                ('final_decision', models.CharField(max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liveness_audits', to='employees.employee')),
            ],
        ),
    ]
